name: Build Mod

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Verify wrapper exists
        run: ls -R

      - name: Build mod
        run: bash ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/libs/*.jar
